name: app_ahorro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  charts_flutter: ^0.12.0
  fl_chart: ^0.68.0
  http: ^1.2.2
  intl: ^0.17.0
  flutter_dotenv: ^5.1.0
  firebase_core: ^2.24.2
  sqlite3: ^2.3.3+1
  get: ^4.6.6
  sqflite: ^2.3.3+1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/
     


