name: app_ahorro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  charts_flutter: ^0.12.0
  fl_chart: ^0.68.0
  http: ^1.2.2
  intl: ^0.17.0
  flutter_dotenv: ^5.1.0
  sqlite3: ^2.4.6
  get: ^4.6.6
  sqflite: ^2.3.3+1
  animated_floating_buttons: ^0.0.1
  email_validator: ^3.0.0
  water_bottle: ^0.0.7
  liquid_progress_indicator_v2: ^0.5.0
  shared_preferences: ^2.0.11
  uuid: ^4.4.2




  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/
     


